stages: 
    data_ingestion:
      cmd: python src/CarPrediction/pipeline/stage01_data_ingestion.py
      deps:
        - src/CarPrediction/pipeline/stage01_data_ingestion.py
        - config/config.yaml
      outs:
        - artifacts/data_ingestion/CleanedCar_main.csv

    data_validation:
      cmd: python src/CarPrediction/pipeline/stage02_data_validation.py
      deps:
        - src/CarPrediction/pipeline/stage01_data_ingestion.py
        - src/CarPrediction/pipeline/stage02_data_validation.py
      outs:
        - artifacts/data_validation/status.txt 

    data_transformation:
      cmd: python src/CarPrediction/pipeline/stage03_data_transformation.py
      deps:
        - src/CarPrediction/pipeline/stage01_data_ingestion.py
        - src/CarPrediction/pipeline/stage03_data_transformation.py
      outs:
        - artifacts/data_transformation/test.csv
        - artifacts/data_transformation/train.csv

    model_trainer:
      cmd: python src/CarPrediction/pipeline/stage04_model_trainer.py
      deps:
        - src/CarPrediction/pipeline/stage03_data_transformation.py
        - src/CarPrediction/pipeline/stage04_model_trainer.py
      outs:
        - artifacts/model_trainer/model.joblib
